cplusplus:
	webots worlds/standard.wbt &
	/usr/local/webots/webots-controller --stdout-redirect controllers/cplusplus/cplusplus

cpptakeoff:
	webots worlds/standard.wbt &
	/usr/local/webots/webots-controller --stdout-redirect controllers/cpptakeoff/cpptakeoff

haskell:
	webots worlds/standard.wbt &
	/usr/local/webots/webots-controller --stdout-redirect controllers/haskell/haskell

python:
	webots worlds/standard.wbt &
	/usr/local/webots/webots-controller --stdout-redirect controllers/python/python.py

pytakeoff:
	webots worlds/standard.wbt &
	/usr/local/webots/webots-controller --stdout-redirect controllers/pytakeoff/pytakeoff.py

playback-motors:
	webots worlds/standard.wbt &
	/usr/local/webots/webots-controller --stdout-redirect controllers/playback-motors/playback-motors.py

playback-demands:
	webots worlds/standard.wbt &
	/usr/local/webots/webots-controller --stdout-redirect controllers/playback-demands/playback-demands.py

playback-pose:
	webots worlds/supervised.wbt &
	/usr/local/webots/webots-controller --stdout-redirect controllers/playback-pose/playback-pose.py
