#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>

#include "array.h" /* Generated by our specification */

void func (bool value[2]) {

    printf("%s\n", value[0] ? "true" : "false");
}

int main (int argc, char *argv[]) {
    for (;;) {
        step();
    }
    return 0;
}
