#include <stdint.h>
#include <stdio.h>

#include "heater.h" /* Generated by our specification */

float temperature;

static float readTemperature(void)
{
    static float val;
    static int8_t dir;

    // init
    if (val == 0) {
        val = 10;
    }

    if (val == 10) {
        dir = +1;
    }

    if (val == 30) {
        dir = -1;
    }

    val += dir;

    return val;
}

void heaton (float temp) {

    printf("%3.1f => on\n", temp);
}

void heatoff (float temp) {
    
    printf("%3.1f => off\n", temp);
}

int main (int argc, char *argv[]) {
    for (;;) {
        temperature = readTemperature(); /* Dummy function to read a byte from a sensor. */
        step();
    }
    return 0;
}
