obj-y += bosch/
obj-y += hal/
obj-y += free_rtos/
obj-y += stm32f4/

obj-y += debug.o
obj-y += imu.o
obj-y += main.o
obj-y += motors.o
obj-y += uart.o
obj-y += vapplication.o
obj-y += zranger.o

obj-y += copilot_core.o
