obj-y += arduino/
obj-y += bosch_sensors/
obj-y += crtp/
obj-y += hal/
obj-y += platform/
obj-y += stm32f4/
obj-y += tasks/

obj-y += bootloader.o
obj-y += cfassert.o
obj-y += console.o
obj-y += led.o
obj-y += ledseq.o
obj-y += main.o
obj-y += mem.o
obj-y += onewire.o
obj-y += params.o
obj-y += storage.o
obj-y += sysload.o
obj-y += system.o
obj-y += vl53l1_crazyflie.o

### Rules for handling generated version.c
obj-y += version.o
version-objs := version_gen.o
src/version_gen.c: src/version.vtpl FORCE
	 $(PYTHON) $(srctree)/tools/make/versionTemplate.py --crazyflie-base $(srctree) $< $@
